name: Reusable Workflow

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string  
      branch:
        required: false
        type: string
        default: master
    secrets:
      GH_TOKEN:
        required: true

jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Checkout another repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_name }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GH_TOKEN }}
          path: other-repo

      - name: echo message
        run: |
          echo "this is mine"
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync files from ${{ inputs.repo_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
